spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/ireimburse?serverTimezone=UTC
#    username: root
#    password:


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: true


  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB