spring:
  datasource:
    url: jdbc:oracle:thin:@${vcap.services.oracle-database-service.credentials.url}
    username: ${vcap.services.oracle-database-service.credentials.username}
    password: ${vcap.services.oracle-database-service.credentials.password}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: true


  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB